# Generated by Django 5.2.1 on 2025-12-25 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serviceproviderapp', '0003_providerprofile_stripe_connected_and_more'),
        ('servicereceiverapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_description', models.TextField(blank=True, null=True)),
                ('service_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_timeline', models.CharField(max_length=255)),
                ('terms_conditions', models.TextField(blank=True, null=True)),
                ('quotation_status', models.CharField(choices=[('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='sent', max_length=20)),
                ('urgency_type', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0.99, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceproviderapp.providerprofile')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicereceiverapp.receiverprofile')),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='serviceproviderapp.servicecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_description', models.TextField(blank=True, null=True)),
                ('service_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_time_taken', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='active', max_length=20)),
                ('payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('released', 'Released'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('urgency_type', models.CharField(default='normal', max_length=20)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceproviderapp.providerprofile')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicereceiverapp.receiverprofile')),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='serviceproviderapp.servicecategory')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quoteapp.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quoteapp.order')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceproviderapp.providerprofile')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicereceiverapp.receiverprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('stripe_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('platform_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('provider_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('hold', 'Hold'), ('released', 'Released'), ('refunded', 'Refunded')], default='hold', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quoteapp.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
