# Generated by Django 5.2.1 on 2025-12-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='platform_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
