# Generated by Django 5.2.1 on 2026-01-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0002_order_platform_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_request_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_requested_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
