# Generated by Django 5.2.1 on 2026-01-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0003_order_cancellation_request_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
