# Generated by Django 5.2.1 on 2026-01-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0004_quotation_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
