# Generated by Django 5.2.1 on 2025-12-14 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_description', models.TextField(blank=True, null=True)),
                ('provider_experience', models.IntegerField(blank=True, null=True)),
                ('provider_done_work', models.IntegerField(default=0)),
                ('provider_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('provider_service_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('provider_language', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_licence_number', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_country', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_city', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_service_area', models.TextField(blank=True, null=True)),
                ('provider_total_hired', models.IntegerField(default=0)),
                ('provider_total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('provider_available_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('provider_stripe_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='serviceproviderapp.servicecategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderKeyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=100)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceproviderapp.providerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderDocument',
            fields=[
                ('document_id', models.IntegerField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID Card'), ('driving_licence', 'Driving Licence')], max_length=100)),
                ('document_front', models.CharField(max_length=255)),
                ('verification_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceproviderapp.providerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderWorkImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='provider_work_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_images', to='serviceproviderapp.providerprofile')),
            ],
        ),
    ]
