# Generated by Django 5.2.1 on 2025-12-18 11:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviderapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerdocument',
            name='document_id',
        ),
        migrations.AddField(
            model_name='providerdocument',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
