# Generated by Django 5.2.1 on 2025-12-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviderapp', '0002_remove_providerdocument_document_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='stripe_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='stripe_connection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
