# Generated by Django 5.2.1 on 2026-04-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviderapp', '0004_bankdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='routing_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='provider_profile_setup_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='provider_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='provider_zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
