# Generated by Django 5.2.1 on 2026-04-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviderapp', '0005_bankdetails_routing_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='bank_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
