# Generated by Django 5.2.1 on 2025-12-27 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serviceproviderapp', '0003_providerprofile_stripe_connected_and_more'),
        ('servicereceiverapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversation_id', models.AutoField(primary_key=True, serialize=False)),
                ('conversation_status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceproviderapp.providerprofile')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicereceiverapp.receiverprofile')),
            ],
            options={
                'unique_together': {('receiver', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('message_image', models.CharField(blank=True, max_length=255, null=True)),
                ('message_file', models.CharField(blank=True, max_length=255, null=True)),
                ('message_voice', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messageapp.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
