# Generated by Django 5.2.1 on 2025-12-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_file',
            field=models.FileField(blank=True, null=True, upload_to='messages/files/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_image',
            field=models.ImageField(blank=True, null=True, upload_to='messages/images/'),
        ),
    ]
